# docker-compose.yml

version: '3.8'
services:
  prompt-chain-management:
    image: prompt-chain-management:latest
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/app
    command: uvicorn src.main:app --host 0.0.0.0 --port 80 --reload
